graph LR
  community_110(["engine +15 dirs\n1225"])
  community_219(["engine +17 dirs\n913"])
  community_243(["pipeline +11 dirs\n677"])
  community_224(["reader +14 dirs\n536"])
  community_233(["daemon +16 dirs\n524"])
  community_236(["cli +7 dirs\n400"])
  community_70(["index +3 dirs\n374"])
  community_230(["engine +14 dirs\n371"])
  community_128(["protobuf/runtime +2 dirs\n366"])
  community_173(["caption +6 dirs\n360"])
  community_235(["cli +9 dirs\n347"])
  community_109(["engine +5 dirs\n328"])
  community_246(["eval +5 dirs\n315"])
  community_30(["engine +2 dirs · Query\n287"])
  community_107(["engine +9 dirs\n284"])
  community_66(["grpc +5 dirs\n266"])
  community_217(["engine +6 dirs · append\n248"])
  community_100(["rest +2 dirs · writeJSON\n244"])
  community_37(["proto/gen +4 dirs\n204"])
  community_250(["reader +6 dirs · TrimSpace\n193"])

  community_100 -->|2| community_107
  community_100 -->|3| community_109
  community_100 -->|5| community_110
  community_100 -->|2| community_173
  community_100 -->|1| community_217
  community_100 -->|7| community_219
  community_100 -->|3| community_224
  community_100 -->|1| community_230
  community_100 -->|1| community_233
  community_100 -->|2| community_235
  community_100 -->|1| community_236
  community_100 -->|1| community_246
  community_100 -->|1| community_250
  community_100 -->|3| community_30
  community_107 -->|5| community_109
  community_107 -->|21| community_110
  community_107 -->|2| community_173
  community_107 -->|6| community_217
  community_107 -->|21| community_219
  community_107 -->|10| community_224
  community_107 -->|3| community_230
  community_107 -->|2| community_233
  community_107 -->|1| community_236
  community_107 -->|3| community_243
  community_107 -->|3| community_246
  community_107 -->|1| community_250
  community_107 -->|4| community_30
  community_107 -->|3| community_70
  community_109 -->|21| community_107
  community_109 -->|5| community_110
  community_109 -->|4| community_173
  community_109 -->|10| community_217
  community_109 -->|20| community_219
  community_109 -->|6| community_224
  community_109 -->|2| community_230
  community_109 -->|2| community_233
  community_109 -->|1| community_236
  community_109 -->|1| community_250
  community_109 -->|2| community_70
  community_110 -->|27| community_107
  community_110 -->|25| community_109
  community_110 -->|10| community_173
  community_110 -->|13| community_217
  community_110 -->|93| community_219
  community_110 -->|11| community_224
  community_110 -->|87| community_230
  community_110 -->|13| community_233
  community_110 -->|3| community_235
  community_110 -->|16| community_236
  community_110 -->|69| community_243
  community_110 -->|8| community_246
  community_110 -->|6| community_250
  community_110 -->|46| community_30
  community_110 -->|4| community_37
  community_110 -->|8| community_66
  community_110 -->|14| community_70
  community_128 -->|3| community_173
  community_173 -->|2| community_109
  community_173 -->|6| community_110
  community_173 -->|4| community_217
  community_173 -->|10| community_219
  community_173 -->|1| community_230
  community_173 -->|10| community_233
  community_173 -->|1| community_235
  community_173 -->|2| community_250
  community_173 -->|1| community_30
  community_173 -->|22| community_37
  community_217 -->|4| community_107
  community_217 -->|1| community_109
  community_217 -->|3| community_110
  community_217 -->|1| community_173
  community_217 -->|20| community_219
  community_217 -->|4| community_224
  community_217 -->|1| community_230
  community_217 -->|5| community_233
  community_217 -->|1| community_236
  community_217 -->|1| community_243
  community_217 -->|1| community_246
  community_217 -->|4| community_250
  community_217 -->|1| community_30
  community_219 -->|4| community_107
  community_219 -->|7| community_109
  community_219 -->|77| community_110
  community_219 -->|4| community_173
  community_219 -->|44| community_217
  community_219 -->|5| community_224
  community_219 -->|41| community_230
  community_219 -->|12| community_233
  community_219 -->|12| community_235
  community_219 -->|7| community_236
  community_219 -->|11| community_243
  community_219 -->|1| community_246
  community_219 -->|16| community_250
  community_219 -->|22| community_30
  community_224 -->|3| community_107
  community_224 -->|8| community_109
  community_224 -->|9| community_110
  community_224 -->|1| community_173
  community_224 -->|5| community_217
  community_224 -->|23| community_219
  community_224 -->|8| community_230
  community_224 -->|12| community_233
  community_224 -->|17| community_235
  community_224 -->|6| community_236
  community_224 -->|13| community_243
  community_224 -->|2| community_246
  community_224 -->|16| community_250
  community_230 -->|4| community_107
  community_230 -->|7| community_109
  community_230 -->|42| community_110
  community_230 -->|2| community_173
  community_230 -->|7| community_217
  community_230 -->|47| community_219
  community_230 -->|4| community_224
  community_230 -->|4| community_233
  community_230 -->|4| community_235
  community_230 -->|9| community_236
  community_230 -->|9| community_243
  community_230 -->|1| community_246
  community_230 -->|2| community_250
  community_230 -->|7| community_30
  community_233 -->|1| community_100
  community_233 -->|5| community_107
  community_233 -->|5| community_109
  community_233 -->|24| community_110
  community_233 -->|5| community_173
  community_233 -->|4| community_217
  community_233 -->|20| community_219
  community_233 -->|11| community_224
  community_233 -->|1| community_230
  community_233 -->|5| community_235
  community_233 -->|6| community_236
  community_233 -->|29| community_243
  community_233 -->|6| community_246
  community_233 -->|15| community_250
  community_233 -->|2| community_66
  community_235 -->|1| community_100
  community_235 -->|2| community_107
  community_235 -->|1| community_109
  community_235 -->|5| community_110
  community_235 -->|2| community_173
  community_235 -->|6| community_217
  community_235 -->|37| community_219
  community_235 -->|8| community_224
  community_235 -->|9| community_230
  community_235 -->|13| community_233
  community_235 -->|23| community_236
  community_235 -->|3| community_243
  community_235 -->|2| community_246
  community_235 -->|6| community_250
  community_235 -->|2| community_30
  community_235 -->|2| community_66
  community_236 -->|1| community_100
  community_236 -->|16| community_107
  community_236 -->|3| community_109
  community_236 -->|35| community_110
  community_236 -->|7| community_217
  community_236 -->|38| community_219
  community_236 -->|8| community_224
  community_236 -->|9| community_230
  community_236 -->|17| community_233
  community_236 -->|20| community_235
  community_236 -->|24| community_243
  community_236 -->|4| community_246
  community_236 -->|1| community_30
  community_236 -->|2| community_70
  community_243 -->|21| community_107
  community_243 -->|49| community_110
  community_243 -->|2| community_173
  community_243 -->|4| community_217
  community_243 -->|24| community_219
  community_243 -->|22| community_224
  community_243 -->|45| community_230
  community_243 -->|27| community_233
  community_243 -->|7| community_235
  community_243 -->|39| community_236
  community_243 -->|7| community_246
  community_243 -->|1| community_250
  community_243 -->|2| community_70
  community_246 -->|4| community_107
  community_246 -->|24| community_110
  community_246 -->|7| community_217
  community_246 -->|10| community_219
  community_246 -->|9| community_230
  community_246 -->|13| community_233
  community_246 -->|2| community_235
  community_246 -->|2| community_236
  community_246 -->|4| community_243
  community_246 -->|1| community_250
  community_246 -->|1| community_30
  community_250 -->|2| community_109
  community_250 -->|15| community_110
  community_250 -->|1| community_173
  community_250 -->|9| community_217
  community_250 -->|17| community_219
  community_250 -->|5| community_224
  community_250 -->|3| community_233
  community_250 -->|1| community_236
  community_30 -->|7| community_107
  community_30 -->|1| community_109
  community_30 -->|41| community_110
  community_30 -->|5| community_217
  community_30 -->|31| community_219
  community_30 -->|4| community_224
  community_30 -->|23| community_230
  community_30 -->|3| community_233
  community_30 -->|1| community_236
  community_30 -->|1| community_243
  community_30 -->|1| community_246
  community_30 -->|4| community_70
  community_37 -->|1| community_128
  community_37 -->|21| community_217
  community_66 -->|41| community_110
  community_66 -->|2| community_128
  community_66 -->|3| community_173
  community_66 -->|1| community_217
  community_66 -->|2| community_219
  community_66 -->|16| community_230
  community_66 -->|1| community_236
  community_66 -->|6| community_243
  community_66 -->|1| community_37
  community_66 -->|1| community_70
  community_70 -->|2| community_107
  community_70 -->|1| community_109
  community_70 -->|2| community_110
  community_70 -->|10| community_217
  community_70 -->|56| community_219
  community_70 -->|13| community_230
  community_70 -->|3| community_243
